version: '3.7'
services:
    mongodb:
        image: mongo:latest
        ports:
            - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
        volumes:
            - mongodb_data_container:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    app:
        depends_on:
            - mongodb
        build: .
        restart: unless-stopped
        env_file: ./.env
        ports:
            - "127.0.0.1:$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
        environment:
            - DB_HOST=mongodb
            - DB_USER=$MONGODB_USER
            - DB_PASSWORD=$MONGODB_PASSWORD
            - DB_NAME=$MONGODB_DATABASE
            - DB_PORT=$MONGODB_DOCKER_PORT
        stdin_open: true
        tty: true
        volumes:
            - ./:/usr/app
            - ignore:/usr/app/node_modules/
volumes:
    mongodb_data_container:
    ignore:
